### ISSUE TITLE
About Modal Needs Some Tweaks

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#355]
The header text has "..." at the end. We need to remove that.

The text within the body of the modal touches the edge of the modal. A 1-2 px buffer would improve that.

![image](https://github.com/Bearsampp/Bearsampp/assets/12568201/d8ffd000-596c-46f9-8247-6d672a385dca)

**Comment by N6REJ** [comment]
This is resolved?

**Comment by jwaisner** [comment]
No this is not. Still showing right up against the edge of the box.

![image](https://github.com/Bearsampp/Bearsampp/assets/12568201/7440077e-0fdd-49fb-b4dd-4b25acd24ef7)

**Comment by N6REJ** [comment]
fixed
